#!/bin/sh

# PROVIDE: nad
# REQUIRE: LOGIN NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=nad
rcvar="${name}_enable"
pidfile="@@PID_FILE@@"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

nad_start()
{
    echo "Starting ${name}."
    export PATH="$PATH:/usr/local/bin:/usr/local/sbin"
    @@SBIN@@/nad --daemon --pid_file $pidfile @@SYSLOG@@
}

nad_stop()
{
    echo "Stopping ${name}."
    kill $(cat $pidfile)
}

load_rc_config $name
run_rc_command "$1"
