#!/bin/sh

# PROVIDE: nad
# REQUIRE: LOGIN NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=nad
rcvar=nad_enable
command="@@PREFIX@@/sbin/nad"
command_interpreter="node"
start_precmd="nad_precmd"
start_cmd="nad_start"

load_rc_config $name
: ${nad_enable:="yes"}
: ${nad_flags:="-c @@CONF@@"}

nad_precmd()
{
    rc_flags="${nad_flags}"
}

nad_start()
{
    PATH="@@PREFIX@@/embedded/bin:@@PREFIX@@/sbin:$PATH"
    NODE_PATH="@@PREFIX@@/lib/node_modules"
    export PATH NODE_PATH

    echo "Starting ${name}."
    daemon -f -u nobody @@PREFIX@@/sbin/nad $rc_flags
}

run_rc_command "$1"
