#!/bin/bash
#
# nad        Startup script for Circonus node agent daemon
#
# chkconfig: - 98 02
# description: Circonus node agent daemon
# processname: nad
#
### BEGIN INIT INFO
# Provides:          nad
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A very thin, simply managed host agent written in Node.js
# Description:       The node-agent daemon provides a simple mechanism to expose
#                    systems and application metrics to external onlookers.
#                    It inventories all executable programs in its config directory
#                    and executes them upon external request, returning results
#                    in JSON format.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="Circonus node agent daemon"
NAD=/opt/circonus/sbin/nad
NAD_OPTS=''
NAD_DEFAULTS_FILE=/etc/sysconfig/nad
NAD_PIDFILE=/var/run/nad
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-60}

if [ -s $NAD_DEFAULTS_FILE ]; then
	. $NAD_DEFAULTS_FILE
fi

export PATH=/opt/circonus/sbin:/opt/omni/bin:$PATH
export NODE_PATH=/opt/circonus/etc/node_modules

run_app() {
        runuser -p -c "nohup $NAD $NAD_OPTS >/dev/null 2>&1 &" nobody
	RETVAL=$?
	if [[ "$RETVAL" == "0" ]]; then
		pid=$(pgrep -f $NAD)
		echo $pid > $NAD_PIDFILE
		success
	else
		failure
	fi
	return $RETVAL
}

start() {
        echo -n $"Starting $prog: "
	__pids_var_run nad $NAD_PIDFILE
	RETVAL=$?
	if [[ "$RETVAL" == "3" ]]; then
		# Not running, so start
		run_app
		RETVAL=$?
	elif [[ "$RETVAL" == "1" ]]; then
		# Stale pidfile
		rm $NAD_PIDFILE 
		run_app
		RETVAL=$?
	else
		# Already running
		success
		RETVAL=0
	fi
        echo
        return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc -p $NAD_PIDFILE
	RETVAL=$?
	echo
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p $NAD_PIDFILE $NAD
	RETVAL=$?
	;;
  reload|force-reload)
	echo "Reloading Circonus node agent daemon: not needed, as there is no config file."
	;;
  restart)
	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|reload|force-reload|status|restart}"
	RETVAL=2
esac

exit $RETVAL
